// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjs1xigCDgCiMast3V5IiLoR1sPjGStJE',
    appId: '1:805064063124:web:52940fe2f3df3c44c95c81',
    messagingSenderId: '805064063124',
    projectId: 'onesignal-644b2',
    authDomain: 'onesignal-644b2.firebaseapp.com',
    storageBucket: 'onesignal-644b2.appspot.com',
    measurementId: 'G-SKW1DJNN6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1xVihSQ8o2VuWGnNxwBGUfK_byMP-Zig',
    appId: '1:805064063124:android:6e7130c5ed6bef50c95c81',
    messagingSenderId: '805064063124',
    projectId: 'onesignal-644b2',
    storageBucket: 'onesignal-644b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFNI8wda6BHnHFk-jlvEfh2YNuoTQ2pYg',
    appId: '1:805064063124:ios:80ea77dd05c1897bc95c81',
    messagingSenderId: '805064063124',
    projectId: 'onesignal-644b2',
    storageBucket: 'onesignal-644b2.appspot.com',
    iosClientId: '805064063124-tele6tome972422qkadjctov2ok44tb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOnesignalExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFNI8wda6BHnHFk-jlvEfh2YNuoTQ2pYg',
    appId: '1:805064063124:ios:97952fa8f7027d89c95c81',
    messagingSenderId: '805064063124',
    projectId: 'onesignal-644b2',
    storageBucket: 'onesignal-644b2.appspot.com',
    iosClientId: '805064063124-p86i4sd1fhgs084gqjn2sdegqh64sjp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterOnesignalExample.RunnerTests',
  );
}
